// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uzadusczqrhuvuerztum.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6YWR1c2N6cXJodXZ1ZXJ6dHVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NzA0ODIsImV4cCI6MjA2MTM0NjQ4Mn0.EaZTf3jv6cnwkKSh9lTXd3G4392t9NEvS25qEKD1I-A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);