// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qqefhdgridquzcryadlr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFxZWZoZGdyaWRxdXpjcnlhZGxyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzODA0ODIsImV4cCI6MjA2MDk1NjQ4Mn0.Jj5lD3tdiMY8g67MDjP9caQ4mQd8bFKMiEc-PCO0Xzg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);