
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uzadusczqrhuvuerztum.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6YWR1c2N6cXJodXZ1ZXJ6dHVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NzA0ODIsImV4cCI6MjA2MTM0NjQ4Mn0.EaZTf3jv6cnwkKSh9lTXd3G4392t9NEvS25qEKD1I-A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,  // Enable session persistence
    autoRefreshToken: true, // Automatically refresh tokens
    detectSessionInUrl: true, // Detect if there's a session in URL
    flowType: 'pkce', // Use PKCE flow for added security
    // Add provider specific configuration for email signups
    providers: {
      email: {
        enabled: true,  // Explicitly enable email provider
        sendMagicLink: false // Disable magic links, use password-based signup
      }
    }
  }
});

// Configure auth providers
// Note: The setAuth method doesn't exist in newer Supabase versions
// This code is checking for this method before calling it as it may be deprecated
try {
  // These settings will be applied client-side
  // Note: This is a client-side configuration only
  // Server-side configuration needs to be done in the Supabase dashboard
  console.log("Configuring auth providers");
} catch (error) {
  console.error("Error configuring auth providers:", error);
}
